{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\balaj\\AppData\\Local\\Temp\\ipykernel_24260\\155640830.py\", line 89, in search_contact\n",
      "    self.populate_contact_treeview(results)\n",
      "TypeError: ContactBookApp.populate_contact_treeview() takes 1 positional argument but 2 were given\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import json\n",
    "import tkinter as tk\n",
    "from tkinter import ttk, messagebox, filedialog\n",
    "\n",
    "class ContactBookApp:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Contact Book\")\n",
    "        self.contacts = {}\n",
    "        self.load_contacts()\n",
    "\n",
    "        self.create_menu()\n",
    "        self.create_toolbar()\n",
    "        self.create_main_frame()\n",
    "        self.create_contact_treeview()\n",
    "        self.create_search_frame()\n",
    "\n",
    "    def load_contacts(self):\n",
    "        if os.path.exists(\"contacts.json\"):\n",
    "            with open(\"contacts.json\", \"r\") as file:\n",
    "                self.contacts = json.load(file)\n",
    "\n",
    "    def save_contacts(self):\n",
    "        with open(\"contacts.json\", \"w\") as file:\n",
    "            json.dump(self.contacts, file, indent=4)\n",
    "\n",
    "    def create_menu(self):\n",
    "        menubar = tk.Menu(self.root)\n",
    "        filemenu = tk.Menu(menubar, tearoff=0)\n",
    "        filemenu.add_command(label=\"Import Contacts\", command=self.import_contacts)\n",
    "        filemenu.add_command(label=\"Export Contacts\", command=self.export_contacts)\n",
    "        filemenu.add_separator()\n",
    "        filemenu.add_command(label=\"Exit\", command=self.root.quit)\n",
    "        menubar.add_cascade(label=\"File\", menu=filemenu)\n",
    "        self.root.config(menu=menubar)\n",
    "\n",
    "    def create_toolbar(self):\n",
    "        toolbar = ttk.Frame(self.root)\n",
    "        add_button = ttk.Button(toolbar, text=\"Add Contact\", command=self.add_contact)\n",
    "        add_button.pack(side=tk.LEFT, padx=5, pady=5)\n",
    "        edit_button = ttk.Button(toolbar, text=\"Edit Contact\", command=self.edit_contact)\n",
    "        edit_button.pack(side=tk.LEFT, padx=5, pady=5)\n",
    "        delete_button = ttk.Button(toolbar, text=\"Delete Contact\", command=self.delete_contact)\n",
    "        delete_button.pack(side=tk.LEFT, padx=5, pady=5)\n",
    "        toolbar.pack(side=tk.TOP, fill=tk.X)\n",
    "\n",
    "    def create_main_frame(self):\n",
    "        self.main_frame = ttk.Frame(self.root)\n",
    "        self.main_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)\n",
    "\n",
    "    def create_contact_treeview(self):\n",
    "        self.contacts_treeview = ttk.Treeview(self.main_frame, columns=(\"Phone\", \"Email\", \"Address\"))\n",
    "        self.contacts_treeview.heading(\"#0\", text=\"Name\")\n",
    "        self.contacts_treeview.heading(\"Phone\", text=\"Phone\")\n",
    "        self.contacts_treeview.heading(\"Email\", text=\"Email\")\n",
    "        self.contacts_treeview.heading(\"Address\", text=\"Address\")\n",
    "        self.contacts_treeview.column(\"#0\", width=150)\n",
    "        self.contacts_treeview.column(\"Phone\", width=120)\n",
    "        self.contacts_treeview.column(\"Email\", width=200)\n",
    "        self.contacts_treeview.column(\"Address\", width=300)\n",
    "        self.contacts_treeview.pack(fill=tk.BOTH, expand=True)\n",
    "        self.contacts_treeview.bind(\"<Double-1>\", self.edit_contact)\n",
    "        self.contacts_treeview.bind(\"<Delete>\", self.delete_contact)\n",
    "        self.populate_contact_treeview()\n",
    "\n",
    "    def populate_contact_treeview(self):\n",
    "        self.contacts_treeview.delete(*self.contacts_treeview.get_children())\n",
    "        for name, info in self.contacts.items():\n",
    "            self.contacts_treeview.insert(\"\", \"end\", text=name, values=(info[\"phone\"], info[\"email\"], info[\"address\"]))\n",
    "\n",
    "    def create_search_frame(self):\n",
    "        search_frame = ttk.Frame(self.main_frame)\n",
    "        search_frame.pack(fill=tk.X, pady=(10, 0))\n",
    "\n",
    "        ttk.Label(search_frame, text=\"Search:\").pack(side=tk.LEFT, padx=(0, 5))\n",
    "        self.search_entry = ttk.Entry(search_frame)\n",
    "        self.search_entry.pack(side=tk.LEFT, fill=tk.X, expand=True)\n",
    "        search_button = ttk.Button(search_frame, text=\"Search\", command=self.search_contact)\n",
    "        search_button.pack(side=tk.LEFT)\n",
    "\n",
    "def search_contact(self):\n",
    "    query = self.search_entry.get().lower()\n",
    "    if query:\n",
    "        results = {}\n",
    "        for name, info in self.contacts.items():\n",
    "            if query in name.lower() or query in info[\"phone\"]:\n",
    "                results[name] = info\n",
    "        self.populate_contact_treeview(results)\n",
    "    else:\n",
    "        self.populate_contact_treeview(self.contacts)\n",
    "\n",
    "    def add_contact(self):\n",
    "        add_edit_window = AddEditContactWindow(self.root)\n",
    "        self.root.wait_window(add_edit_window.top)\n",
    "        if add_edit_window.contact_data:\n",
    "            self.contacts[add_edit_window.contact_data[\"name\"]] = add_edit_window.contact_data\n",
    "            self.populate_contact_treeview()\n",
    "            self.save_contacts()\n",
    "\n",
    "    def edit_contact(self, event=None):\n",
    "        selected_item = self.contacts_treeview.selection()\n",
    "        if selected_item:\n",
    "            name = self.contacts_treeview.item(selected_item, \"text\")\n",
    "            add_edit_window = AddEditContactWindow(self.root, name=name, data=self.contacts[name])\n",
    "            self.root.wait_window(add_edit_window.top)\n",
    "            if add_edit_window.contact_data:\n",
    "                del self.contacts[name]\n",
    "                self.contacts[add_edit_window.contact_data[\"name\"]] = add_edit_window.contact_data\n",
    "                self.populate_contact_treeview()\n",
    "                self.save_contacts()\n",
    "\n",
    "    def delete_contact(self, event=None):\n",
    "        selected_item = self.contacts_treeview.selection()\n",
    "        if selected_item:\n",
    "            name = self.contacts_treeview.item(selected_item, \"text\")\n",
    "            confirm = messagebox.askyesno(\"Delete Contact\", f\"Are you sure you want to delete {name}?\")\n",
    "            if confirm:\n",
    "                del self.contacts[name]\n",
    "                self.populate_contact_treeview()\n",
    "                self.save_contacts()\n",
    "\n",
    "    def import_contacts(self):\n",
    "        filename = filedialog.askopenfilename(filetypes=[(\"JSON files\", \"*.json\")])\n",
    "        if filename:\n",
    "            with open(filename, \"r\") as file:\n",
    "                imported_contacts = json.load(file)\n",
    "                self.contacts.update(imported_contacts)\n",
    "                self.populate_contact_treeview()\n",
    "                self.save_contacts()\n",
    "\n",
    "    def export_contacts(self):\n",
    "        filename = filedialog.asksaveasfilename(defaultextension=\".json\", filetypes=[(\"JSON files\", \"*.json\")])\n",
    "        if filename:\n",
    "            with open(filename, \"w\") as file:\n",
    "                json.dump(self.contacts, file, indent=4)\n",
    "\n",
    "class AddEditContactWindow:\n",
    "    def __init__(self, parent, name=\"\", data=None):\n",
    "        self.top = tk.Toplevel(parent)\n",
    "        self.top.title(\"Add/Edit Contact\")\n",
    "        self.contact_data = None\n",
    "\n",
    "        ttk.Label(self.top, text=\"Name:\").grid(row=0, column=0, padx=5, pady=5, sticky=\"e\")\n",
    "        ttk.Label(self.top, text=\"Phone:\").grid(row=1, column=0, padx=5, pady=5, sticky=\"e\")\n",
    "        ttk.Label(self.top, text=\"Email:\").grid(row=2, column=0, padx=5, pady=5, sticky=\"e\")\n",
    "        ttk.Label(self.top, text=\"Address:\").grid(row=3, column=0, padx=5, pady=5, sticky=\"e\")\n",
    "\n",
    "        self.name_entry = ttk.Entry(self.top)\n",
    "        self.name_entry.grid(row=0, column=1, padx=5, pady=5)\n",
    "        self.name_entry.insert(0, name)\n",
    "\n",
    "        self.phone_entry = ttk.Entry(self.top)\n",
    "        self.phone_entry.grid(row=1, column=1, padx=5, pady=5)\n",
    "        if data:\n",
    "            self.phone_entry.insert(0, data[\"phone\"])\n",
    "\n",
    "        self.email_entry = ttk.Entry(self.top)\n",
    "        self.email_entry.grid(row=2, column=1, padx=5, pady=5)\n",
    "        if data:\n",
    "            self.email_entry.insert(0, data[\"email\"])\n",
    "\n",
    "        self.address_entry = ttk.Entry(self.top)\n",
    "        self.address_entry.grid(row=3, column=1, padx=5, pady=5)\n",
    "        if data:\n",
    "            self.address_entry.insert(0, data[\"address\"])\n",
    "\n",
    "        save_button = ttk.Button(self.top, text=\"Save\", command=self.save_contact)\n",
    "        save_button.grid(row=4, column=0, columnspan=2, padx=5, pady=10)\n",
    "\n",
    "    def save_contact(self):\n",
    "        name = self.name_entry.get().strip()\n",
    "        phone = self.phone_entry.get().strip()\n",
    "        email = self.email_entry.get().strip()\n",
    "        address = self.address_entry.get().strip()\n",
    "        if name and phone:\n",
    "            self.contact_data = {\"name\": name, \"phone\": phone, \"email\": email, \"address\": address}\n",
    "            self.top.destroy()\n",
    "        else:\n",
    "            messagebox.showerror(\"Error\", \"Name and phone are required.\")\n",
    "\n",
    "def main():\n",
    "    root = tk.Tk()\n",
    "    app = ContactBookApp(root)\n",
    "    root.mainloop()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
